sonata_media:
    class:
        media:              App\Entity\SonataMediaMedia
        gallery:            App\Entity\SonataMediaGallery
        gallery_has_media:  App\Entity\SonataMediaGalleryHasMedia
    db_driver: doctrine_orm #
    default_context: default
    contexts:
        default:
            providers:
                #- sonata.media.provider.dailymotion
                #- sonata.media.provider.youtube
                - sonata.media.provider.image
                #- sonata.media.provider.file
                #- sonata.media.provider.vimeo

            formats:
                small: { width: 400 , quality: 90}
                big:   { width: 400 , quality: 70, resizer: sonata.media.resizer.square}
        product:
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 200 , quality: 80}
                big:   { width: 400 , quality: 70, resizer: sonata.media.resizer.square}


    cdn:
        server:
            path: /upload/media

    filesystem:
        local:
            # Directory for uploads should be writable
            directory: "%kernel.project_dir%/public/upload/media"
            create: false
